### ISSUE TITLE
uninitialized constant ActiveResource::Pagination

### ISSUE THREAD

**Issue by Zeneixe** [jeffmoss/active-resource-pagination#2]
On Rails 4.0.1, I am doing this:
- Add active-resource-pagination to Gemfile
- Run bundle install
- Start application
- Add this line to my Model.rb: include ActiveResource::Pagination

All I get is this error message:

uninitialized constant ActiveResource::Pagination

Am I missing something here?

**Comment by ddarren** [comment]
I'mm getting the same error and I'm also on Rails 4.

**Comment by Zeneixe** [comment]
We just quit using ActiveResource, now we are using (and developing) this:

https://github.com/carwow/restful_resource

**Comment by Formless** [comment]
@Fuffi Could you update the documentation for restful resource?

**Comment by Zeneixe** [comment]
@Formless fair request, I hope I will manage to do it soon, if you have any questions please let me know. If you're interested I suggest you look at the specs/ folder and see some use cases
